name: pyInstaller
on: [push, workflow_dispatch]
jobs:
  create-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - shell: bash
        run: pip install -r requirements.txt
      - shell: bash
        run: pip install pyinstaller
      - shell: bash
        run: pyinstaller piituri.py --clean --noconf -F --dist ./dist
      - uses: actions/upload-artifact@v4
        with:
          name: piituri.exe
          path: ./dist
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v1
          files: ./dist/piituri.exe
